spring.application.name=driver-service
server.port=8082


# MongoDB configuration
spring.data.mongodb.uri=mongodb+srv://cvideshana_db_user:chrishean@cluster0.c4awtjj.mongodb.net/RideLink?appName=Cluster0
spring.mongodb.uri=mongodb+srv://cvideshana_db_user:chrishean@cluster0.c4awtjj.mongodb.net/RideLink?appName=Cluster0
