server:
  port: 8081

spring:
  application:
    name: account-service
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017}
      database: ridelink-accounts

jwt:
  secret: ${JWT_SECRET:mydefaultsecretkey123456789012345}
  expiration: 86400000

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html